platform :ios, '15.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def common_pods
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'MJRefresh'
end

target 'UserList' do
  common_pods
end

target 'UserListTests' do
  common_pods
end

target 'UserListUITests' do
  common_pods
end
